
import React, { useState } from "react";
import { Plus, Minus } from "lucide-react";

const FAQ = () => {
  const [activeIndex, setActiveIndex] = useState<number | null>(null);

  const faqs = [
    {
      question: "What exactly is Taxes GPT?",
      answer:
        "Taxes GPT is an AI assistant specifically trained to help businesses optimize their tax strategies. It provides state-specific tax guidance, helps identify potential deductions, analyzes financial documents, and generates comprehensive tax reports tailored to your business situation.",
    },
    {
      question: "How does Taxes GPT handle my sensitive financial information?",
      answer:
        "Taxes GPT prioritizes data security and privacy. Your financial information is processed with enterprise-grade security measures. The system doesn't store sensitive personal information like social security numbers, and all document analysis is conducted within secure environments.",
    },
    {
      question: "Does Taxes GPT replace my accountant or tax professional?",
      answer:
        "Taxes GPT is designed to be a powerful tool that complements the work of tax professionals, not replace them. The AI can help you prepare, organize, and identify potential deductions, but we recommend consulting with a certified tax professional before filing your taxes.",
    },
    {
      question: "Which states' tax codes does Taxes GPT understand?",
      answer:
        "Taxes GPT is trained on tax codes for all 50 U.S. states and can provide state-specific guidance for each. Simply specify your state of operation during your conversation with the AI.",
    },
    {
      question: "What types of documents can I upload for analysis?",
      answer:
        "You can upload receipts, invoices, bank statements, previous tax returns, profit and loss statements, and other financial documents. The AI will analyze these to categorize expenses and identify potential deductions.",
    },
    {
      question: "How accurate are the tax reports generated by Taxes GPT?",
      answer:
        "Taxes GPT strives for high accuracy by using up-to-date tax information. However, tax laws change frequently, and individual situations vary. The reports should be used as guidance and verified by a tax professional before filing.",
    },
  ];

  const toggleAccordion = (index: number) => {
    setActiveIndex(activeIndex === index ? null : index);
  };

  return (
    <section id="faq" className="py-20 relative bg-cyber-darker">
      <div className="relative z-10 max-w-7xl mx-auto px-6 md:px-12">
        <div className="text-center mb-16">
          <div className="flex justify-center space-x-2 items-center mb-4">
            <div className="h-[1px] w-12 bg-cyber-blue"></div>
            <span className="text-cyber-blue uppercase tracking-wider font-bold text-sm">
              Common Questions
            </span>
            <div className="h-[1px] w-12 bg-cyber-blue"></div>
          </div>
          <h2 className="text-3xl md:text-4xl font-bold mb-4 cyber-font">
            Frequently Asked <span className="cyber-gradient-text">Questions</span>
          </h2>
          <p className="text-gray-300 max-w-3xl mx-auto text-lg">
            Get answers to the most common questions about Taxes GPT and how it can help with your tax needs.
          </p>
        </div>

        <div className="max-w-4xl mx-auto">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className="mb-4 cyber-card rounded-lg overflow-hidden"
            >
              <button
                className="w-full p-6 text-left flex justify-between items-center focus:outline-none"
                onClick={() => toggleAccordion(index)}
              >
                <h3 className="text-lg font-bold cyber-font">
                  {faq.question}
                </h3>
                <div className="ml-4 flex-shrink-0">
                  {activeIndex === index ? (
                    <Minus className="h-5 w-5 text-cyber-blue" />
                  ) : (
                    <Plus className="h-5 w-5 text-cyber-blue" />
                  )}
                </div>
              </button>
              <div
                className={`transition-all duration-300 ease-in-out overflow-hidden ${
                  activeIndex === index ? "max-h-96 opacity-100" : "max-h-0 opacity-0"
                }`}
              >
                <div className="p-6 pt-0 text-gray-300 border-t border-white/10">
                  {faq.answer}
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-12 text-center">
          <p className="text-gray-300 mb-6">
            Still have questions? Get in touch with our support team.
          </p>
          <a
            href="mailto:Contact@ai-webtools.com"
            className="cyber-button rounded-md inline-block"
          >
            <span>Contact Support</span>
          </a>
        </div>
      </div>
    </section>
  );
};

export default FAQ;
